### PR TITLE
Add HARDENEDBSD-MINIMAL kernel config

### PR DESCRIPTION
**Pull request by pkubaj**
This is a MINIMAL FreeBSD kernel config with added HardenedBSD changes.

### CODE REVIEW

**Comment by lattera** [comment]
I can review and take care of this tonight. Thanks for the contribution!

**Review by lattera — CHANGES_REQUESTED** [review]
There seems to be whitespace changes between MINIMAL and HARDENEDBSD-MINIMAL. Can you match the whitespace?

Running `diff -u MINIMAL HARDENEDBSD-MINIMAL` shows the whitespace changes.

**Comment by pkubaj** [comment]
Copy-pasting broke whitespaces. Do you mind if I send this file to you via mail?

**Comment by lattera** [comment]
Feel free. :)

**Comment by pkubaj** [comment]
I sent the kernel config on 16.05 :)

**Comment by lattera** [comment]
This has now been committed, with a few whitespace changes made by me. Thank you very much for the submission!

**Pull request closed without merging**
