### PR TITLE
Releng 12.1 merge

### PR DESCRIPTION
**Pull request by fichtner**
@lattera as discussed, merged with conflicts, to be able to review changes 2430016

Topics are:

* Keep STACKGAP in there and flush out previously reverted ASLR.
* Regen src.conf.5, loosing WITHOUT_PIE visibility for now.
* Revert a bunch of irrelevant whitespace changes.
* WITH_PIE / WITHOUT_PIE code duality, it's always PIE at the moment.
* 0c33c83c fixes a kernel build issue (tested on amd64)
* 12.1-RELEASE-p1

### CODE REVIEW

**Comment by lattera** [comment]
Thank you so very much for working on this! I apologize for the delay. I've officially started looking into this.

**Comment by fichtner** [comment]
No problem! I merged the recent SAs and marked it ready for review. :)

**Comment by lattera** [comment]
I've merged this work into a local branch. I'm building now. I hope to have some initial testing done this weekend, including installation onto a physical system.

**Comment by lattera** [comment]
FreeBSD's PIE work (which is disabled by default) has overridden our PIE work. Fixing that now.

**Comment by lattera** [comment]
I've now merged this in. Additional testing needs to be performed. I'm gonna keep this PR open until all testing is completed.

**Comment by lattera** [comment]
`paxtest` returns the same results on 12.1-releng/amd64 as it does on 13-current/amd64. Really good sign. :)

**Comment by lattera** [comment]
The above comment was performed on a Hyper-V VM. Next week, when I'm at the Maryland datacenter, I'll make sure to install on a physical server. Perhaps a Dell R410.

**Comment by fichtner** [comment]
super, thanks! I already run experimental builds of the tree for OPNsense and will pull in the branch to src.git master later this week. ❤️

**Comment by lattera** [comment]
When you get time, can you update the freebsd/12.1-releng/master and hardened/12.1-releng/master branches with any changes from upstream? The former is crucial so that I can diff the branches.

I know, usually our auto-sync scripts do this. I'm hoping to have that back up soon. :-)

**Comment by lattera** [comment]
I've verified that all the proper hardening CFLAGS for 12.1 have been applied to userland. So should OPNsense 20.1 ship with HardenedBSD 12.1, OPNsense will be the first open source enterprise firewall distribution to ship with CFI applied to userland applications. :-)

**Comment by fichtner** [comment]
Sure, direct merge commits or create PRs like this one?

**Comment by lattera** [comment]
Direct merge is fine. Thanks a lot!

**Pull request merged**
