### PR TITLE
Fix build with LibreSSL

### PR DESCRIPTION
**Pull request by pkubaj**

### CODE REVIEW

**Comment by pkubaj** [comment]
PR's are merged now.

**Review by opntr — COMMENTED** [review]
Where is this patch merged?

**Comment by opntr** [comment]
Ahh, I see...

**Comment by opntr** [comment]
Please reopen this issue, if MFC to 11-STABLE is required.

**Comment by opntr** [comment]
And put on the "needs MFC" flag please in this case

**Comment by opntr** [comment]
~~~
commit 99be183341342132ecd4d0eef6ababe2d024a07b
Merge: 25b17c09d60c 22c9018a977b
Author: cy <cy@FreeBSD.org>
Date:   Wed Jul 11 18:53:18 2018 +0000

    MFV r324714:
    
    Update wpa 2.5 --> 2.6.
    
    MFC after:      1 month

Notes:
    svn path=/head/; revision=336203
~~~

Seems like the wpa_supplicant code will be MFCd after a month, so keep this PR open..

**Comment by pkubaj** [comment]
It needs one more bracket, sorry.

**Comment by lattera** [comment]
Is this complete?

**Comment by opntr-auto** [comment]
Keep this open until everything MFCd to 11-stable.

**Comment by pkubaj** [comment]
Yes, it's complete. I've been using a system with those commits for a week.

**Comment by opntr** [comment]
MFC'd to 11-STABLE

**Pull request closed without merging**
