### PR TITLE
Fix build with LibreSSL

### PR DESCRIPTION
**Pull request by pkubaj**
Patches to fix build with LibreSSL after merge of OpenSSL 1.1.1.

### CODE REVIEW

**Comment by opntr** [comment]
It would be nice the elaborate what's happening in the commit and describe this in the commit messages.

And we use the following form:
HBSD: one line summary 

Detailed commit message.. 

Signed-of-by: Your Name <your.name@hardenedbsd.org>

**Comment by opntr** [comment]
There are some trick which makes your life easier :P 

```
op@opn ~> less .gitconfig 
[commit]
        template = ~/.git/hbsd-template
```

```
op@opn ~> cat ~/.git/hbsd-template 
HBSD:


#Signed-off-by: Oliver Pinter <oliver.pinter@hardenedbsd.org>
#github-issue: #
#MFC-to: 
#X-MFC-with:
```

**Comment by lattera** [comment]
Any updates on this PR?

**Comment by lattera** [comment]
OBE

**Pull request closed without merging**
